### PR TITLE
Remove configuredobjects copy on write set

### PR DESCRIPTION
**Pull request by kaaveland**
@smat ?

### CODE REVIEW

**Comment by smat** [comment]
You can probably just remove `append|prepend|reset|...Tag`-functions aswell. Dont think they will work properly without `reconfigure`. Everything else :+1:

**Comment by kaaveland** [comment]
@smat -- deployed this to our nexus with deploy-plugin. I suggest for now that we don't merge this since I can't put the last change into upstream. I'll leave this branch hanging around and get to releasing sporing with this version of constretto.

We probably also want to get around using this version in other apps?

**Comment by smat** [comment]
Yes, this could be a problem in all our apps where we have `@Scope("request")` beans

**Comment by andreaja** [comment]
@kaaveland does this code represent something that is in use by our applications? If so we should merge this pull request and actually maintain our own fork of Constretto. If not, we should delete this repository.

**Comment by kaaveland** [comment]
@andreaja without this patch, sporing has regular crashes due to memory leaks. It's in nexus, upstream doesn't want the patch because they want to implement it themselves. They don't seem to be actually doing that though.

**Comment by andreaja** [comment]
Ok, merging then. We obviously need to keep maintaining our own branch of 2.x until upstream ships 3.0.

**Pull request merged**
